---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - machineset
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - machineset/status
  verbs:
  - get
- apiGroups:
  - instascale.ibm.com.instascale.ibm.com
  resources:
  - appwrappers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instascale.ibm.com.instascale.ibm.com
  resources:
  - appwrappers/finalizers
  verbs:
  - update
- apiGroups:
  - instascale.ibm.com.instascale.ibm.com
  resources:
  - appwrappers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
  resourceNames:
    - instascale-ocm-secret
  resources:
    - secrets
  verbs:
    - get
- apiGroups:
  - config.openshift.io 
  resources:
  - clusterversions
  verbs:
  - get
  - update