apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: instascale
  name: instascale
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instascale
  template:
    metadata:
      labels:
        app: instascale
    spec:
      containers:
      - image: quay.io/project-codeflare/instascale-controller:latest
        name: instascale
        resources:
          limits:
            cpu: "2"
            memory: "2G"
          requests:
            cpu: "2"
            memory: "2G"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            periodSeconds: 10
      serviceAccountName: instascale-sa
